version: 2.1
timezone:
  America/Los_Angeles

jobs:
  style_tests:
    docker:
      - image: chef/chefdk:4.5.0
    working_directory: ~/circulate
    environment:
      GEM_HOME: /opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems
      GEM_PATH: /opt/chefdk/embedded/lib/ruby/gems/2.6.0
      GEM_ROOT: /opt/chefdk/embedded/lib/ruby/gems/2.6.0
      CHEF_LICENSE: accept
    steps:
      - checkout
      - run:
          name: Create Reports Directory
          command: mkdir reports
      - run:
          name: Install Kitchen Docker
          command: chef gem install kitchen-docker -v 2.9.0 --no-user-install --no-document
      - run:
          name: Install Junit Formatter
          command: chef gem install rspec_junit_formatter -v 0.4.1 --no-user-install --no-document
      - run:
          name: CI Debug Outputs
          command: chef gem list | grep -i kitchen && env && ls /opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems | grep kitchen
      - run:
          name: Run Rake Task
          command: /opt/chefdk/embedded/bin/rake style_tests --trace
      - store_test_results:
          path: reports/

  build:
    docker:
      - image: chef/chefdk:4.5.0
    working_directory: ~/circulate
    steps:
      - checkout
      - run:
          name: Message Building
          command: echo 'TODO - BUILD'

  deploy:
    docker:
      - image: chef/chefdk:4.5.0
    working_directory: ~/circulate
    steps:
      - checkout
      - run:
          name: Message Deploying
          command: echo 'TODO - DEPLOY'

workflows:
  version: 2
  # Put in one because not paying for parallel jobs
  style_and_integration:
    jobs:
    - style_tests
    - build:
        requires:
        - style_tests
        filters:
          branches:
            only: master
    - deploy:
        requires:
        - build
        filters:
          branches:
            only: master

